title: FieldTrip toolbox
email: fieldtriptoolbox@gmail.com
description: FieldTrip - the toolbox for MEG, EEG and iEEG

baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fieldtriptoolbx
github_username:  fieldtrip

# Build settings
sass:
  sass_dir: ./static/css

permalink: pretty
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

exclude:
   - README
   - CHANGES
   - TODO
   - Gemfile*
   - bin
